apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: redis-servicemonitor
    release: kube-stack-prometheus
  name: redis-servicemonitor
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: redis-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      release: redis-exporter